title: Tanacross Phrases
description: Tanacross Phrases and Conversations
theme: just-the-docs

url: https://gmholton.github.io/phrases

audiopath: "assets/audio"

exclude:
  - ripped/
  - scripts/
  
#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

back_to_top: true

gh_edit_link: false # show or hide edit this page link

#footer_content: "Copyright &copy; 2003-2023 Irene Solomon Arnold, Gary Holton, and Rick Thoman. <a href='credits.html'>Credits</a>."

number_categories: 28 # total number of categories in categories.csv

color_scheme: color

defaults:
  -
    scope:
      path: "phrases" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "phrase"
      nav_exclude: # true
      parent: Category


search_enabled: false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
